blueprint:
  name: Synchronize HVAC states
  description: Synchronize the state (hvac mode) of 2 climate entities
  domain: automation
  input:
    entity_1:
      name: First entity
      selector:
        entity: 
          domain: climate
    entity_2:
      name: Second entity
      selector:
        entity:
          domain: climate
  source_url: https://github.com/brianewman/ha-blueprint-synchronize-hvac-states/blob/main/ha-blueprint-synchronize-hvac-states.yaml
mode: single
max_exceeded: silent

variables:
  entity_1: !input 'entity_1'
  entity_2: !input 'entity_2'
trigger:
- platform: state
  entity_id: !input 'entity_1'
- platform: state
  entity_id: !input 'entity_2'
condition:
- condition: template
  value_template: '{{ states(entity_1) != states(entity_2) }}'
action:
- service: climate.set_hvac_mode
  target:
    entity_id: '{% if trigger.from_state.entity_id == entity_1 %} {{ entity_2 }} {%
      else %} {{ entity_1 }} {% endif %}'
  data:
    hvac_mode: '{{ trigger.to_state.state }}'
